class CallbackDataManager:
    """ REFRESH START """
    REFRESH = "REFRESH"


    """ PURCHASE FEATURE """
    PURCHASE_FEATURE = "PF"
    CONFIRM_PURCHASE_QUANTITY = "PF_CPQ"
    CONFIRM_PAY_PURCHASE = "PF_CPP"

    RELOAD_QUANTITY_STATE = "PF_RQS"
    TURN_BACK_START_FROM_PURCHASE="PF_TBSFP"
    TURN_BACK_CATEGORY_FROM_QUANTITY="PF_TBCFQ"
    TURN_BACK_QUANTITY_FROM_CONFIRM="PF_TBQFC"



    """ DEPOSIT FEATURE """
    DEPOSIT_FEATURE = "DP"
    TURN_BACK_START_FROM_DEPOSIT = "DP_TBSFD"


    """ ADMIN ADD CATEGORY """
    STOP_ADDING_CATEGORY = "AAC_SAC"


    """ ADMIN ADD PRODUCT """
    ACCEPT_ADDING_PRODUCT = "AAP_AAP"
    CANCEL_ADD_PRODUCT = "AAP_CAP"
    DELETE_PRODUCT = "AAP_DP"
    STOP_ADDING_PRODUCT = "AAP_SAP"